# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(526, 733)
        MainWindow.setMaximumSize(QtCore.QSize(555555, 16777215))
        MainWindow.setStyleSheet("background-color:transparent;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 451, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.log = QtWidgets.QFrame(self.frame)
        self.log.setGeometry(QtCore.QRect(20, 80, 420, 180))
        self.log.setMinimumSize(QtCore.QSize(420, 180))
        self.log.setMaximumSize(QtCore.QSize(420, 180))
        self.log.setStyleSheet("/*background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.051, x2:0.710227, y2:0.335, stop:0 rgba(127, 238, 248, 205), stop:1 rgba(255, 255, 255, 255));*/\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.938, y2:0.380682, stop:0 rgba(232, 170, 127, 255), stop:0.823864 rgba(216, 255, 255, 230));\n"
"border-radius:0px;\n"
"padding:0px;")
        self.log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.log.setObjectName("log")
        self.label = QtWidgets.QLabel(self.log)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:transparent;\n"
"color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.log)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:transparent;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.log)
        self.label_3.setGeometry(QtCore.QRect(310, 0, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.log)
        self.label_4.setGeometry(QtCore.QRect(120, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:transparent;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.log)
        self.label_5.setGeometry(QtCore.QRect(180, 80, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent;")
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.log)
        self.line.setGeometry(QtCore.QRect(40, 70, 200, 3))
        self.line.setMinimumSize(QtCore.QSize(200, 0))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(self.log)
        self.label_6.setGeometry(QtCore.QRect(220, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:transparent;\n"
"color: rgb(170, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.closebtnlog = QtWidgets.QPushButton(self.log)
        self.closebtnlog.setGeometry(QtCore.QRect(390, 0, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.closebtnlog.setFont(font)
        self.closebtnlog.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(170, 0, 0);\n"
"}\n"
"")
        self.closebtnlog.setObjectName("closebtnlog")
        self.errorsms = QtWidgets.QLabel(self.log)
        self.errorsms.setGeometry(QtCore.QRect(20, 0, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.errorsms.setFont(font)
        self.errorsms.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: transparent;")
        self.errorsms.setText("")
        self.errorsms.setAlignment(QtCore.Qt.AlignCenter)
        self.errorsms.setObjectName("errorsms")
        self.log_2 = QtWidgets.QFrame(self.frame)
        self.log_2.setGeometry(QtCore.QRect(50, 260, 350, 140))
        self.log_2.setMinimumSize(QtCore.QSize(350, 140))
        self.log_2.setMaximumSize(QtCore.QSize(350, 140))
        self.log_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.051, x2:0.710227, y2:0.335, stop:0 rgba(127, 238, 248, 205), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:30px;\n"
"border-top-right-radius: 0px; \n"
"border-top-left-radius: 0px;\n"
"padding:0px;")
        self.log_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.log_2.setObjectName("log_2")
        self.pin = QtWidgets.QLineEdit(self.log_2)
        self.pin.setGeometry(QtCore.QRect(10, 70, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(16)
        font.setItalic(True)
        self.pin.setFont(font)
        self.pin.setStyleSheet("background-color: rgba(255, 255, 255,.7);\n"
"border-radius:15px;")
        self.pin.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.pin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pin.setAlignment(QtCore.Qt.AlignCenter)
        self.pin.setDragEnabled(False)
        self.pin.setClearButtonEnabled(True)
        self.pin.setObjectName("pin")
        self.loginbtn = QtWidgets.QPushButton(self.log_2)
        self.loginbtn.setGeometry(QtCore.QRect(270, 20, 61, 91))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.loginbtn.setFont(font)
        self.loginbtn.setStyleSheet("\n"
"QPushButton{\n"
"background-color: transparent;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 170, 127,.8);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"")
        self.loginbtn.setObjectName("loginbtn")
        self.email = QtWidgets.QLineEdit(self.log_2)
        self.email.setGeometry(QtCore.QRect(10, 20, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(14)
        font.setItalic(False)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: rgba(255, 255, 255,.7);\n"
"border-radius:15px;")
        self.email.setInputMethodHints(QtCore.Qt.ImhNone)
        self.email.setText("")
        self.email.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setDragEnabled(False)
        self.email.setClearButtonEnabled(True)
        self.email.setObjectName("email")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.closebtnlog.released.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "COVID "))
        self.label_2.setText(_translate("MainWindow", "TRACKER"))
        self.label_3.setText(_translate("MainWindow", "֎"))
        self.label_4.setText(_translate("MainWindow", "Welcome to"))
        self.label_5.setText(_translate("MainWindow", "Lets make the world a village"))
        self.label_6.setText(_translate("MainWindow", "CoTrac, "))
        self.closebtnlog.setText(_translate("MainWindow", "X"))
        self.pin.setPlaceholderText(_translate("MainWindow", "Enter pin-Code"))
        self.loginbtn.setText(_translate("MainWindow", "LogIn"))
        self.email.setPlaceholderText(_translate("MainWindow", "Enter email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
